import * as React from 'npm:react@18.3.1'
import { renderAsync } from 'npm:@react-email/components@0.0.22'
import { createClient } from 'npm:@supabase/supabase-js@2'
import { corsHeaders } from 'npm:@supabase/supabase-js@2/cors'
import { TEMPLATES } from '../_shared/transactional-email-templates/registry.ts'
const SITE_NAME='nowweseeyou', SENDER_DOMAIN='notify.nowweseeyou.org', FROM_DOMAIN='nowweseeyou.org'
function generateToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return Array.from(bytes).map(b=>b.toString(16).padStart(2,'0')).join('')}
Deno.serve(async(req)=>{if(req.method==='OPTIONS') return new Response(null,{headers:corsHeaders}); const url=Deno.env.get('SUPABASE_URL'), key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'); if(!url||!key) return new Response(JSON.stringify({error:'Server configuration error'}),{status:500,headers:{...corsHeaders,'Content-Type':'application/json'}})
 let templateName:string,recipientEmail:string,idempotencyKey:string,messageId:string,templateData:Record<string,any>={},cc:string[]=[],replyTo:any=null
 try{const b=await req.json();templateName=b.templateName||b.template_name;recipientEmail=b.recipientEmail||b.recipient_email;messageId=crypto.randomUUID();idempotencyKey=b.idempotencyKey||b.idempotency_key||messageId;if(b.templateData&&typeof b.templateData==='object')templateData=b.templateData;if(Array.isArray(b.cc))cc=b.cc.filter((v:unknown):v is string=>typeof v==='string').map((v:string)=>v.trim()).filter(Boolean);if(typeof b.replyTo==='string')replyTo=b.replyTo.trim()||null;else if(b.replyTo&&typeof b.replyTo==='object'&&typeof b.replyTo.address==='string')replyTo={name:typeof b.replyTo.name==='string'?b.replyTo.name:undefined,address:b.replyTo.address.trim()}}catch{return new Response(JSON.stringify({error:'Invalid JSON in request body'}),{status:400,headers:{...corsHeaders,'Content-Type':'application/json'}})}
 const template=TEMPLATES[templateName];if(!template)return new Response(JSON.stringify({error:`Template '${templateName}' not found`}),{status:404,headers:{...corsHeaders,'Content-Type':'application/json'}});const to=template.to||recipientEmail;if(!to)return new Response(JSON.stringify({error:'recipientEmail is required'}),{status:400,headers:{...corsHeaders,'Content-Type':'application/json'}})
 cc=Array.from(new Set(cc.map(x=>x.toLowerCase()).filter(x=>x!==to.toLowerCase()))).slice(0,4);const supabase=createClient(url,key);const {data:suppressed,error:suppressionError}=await supabase.from('suppressed_emails').select('id').eq('email',to.toLowerCase()).maybeSingle();if(suppressionError)return new Response(JSON.stringify({error:'Failed to verify suppression status'}),{status:500,headers:{...corsHeaders,'Content-Type':'application/json'}});if(suppressed)return new Response(JSON.stringify({success:false,reason:'email_suppressed'}),{status:200,headers:{...corsHeaders,'Content-Type':'application/json'}})
 let unsubscribeToken:string;const {data:existing}=await supabase.from('email_unsubscribe_tokens').select('token,used_at').eq('email',to.toLowerCase()).maybeSingle();if(existing&&!existing.used_at)unsubscribeToken=existing.token;else if(!existing){unsubscribeToken=generateToken();await supabase.from('email_unsubscribe_tokens').upsert({token:unsubscribeToken,email:to.toLowerCase()},{onConflict:'email',ignoreDuplicates:true});const {data:stored}=await supabase.from('email_unsubscribe_tokens').select('token').eq('email',to.toLowerCase()).maybeSingle();if(!stored)return new Response(JSON.stringify({error:'Failed to prepare email'}),{status:500,headers:{...corsHeaders,'Content-Type':'application/json'}});unsubscribeToken=stored.token}else return new Response(JSON.stringify({success:false,reason:'email_suppressed'}),{status:200,headers:{...corsHeaders,'Content-Type':'application/json'}})
 const html=await renderAsync(React.createElement(template.component,templateData));const text=await renderAsync(React.createElement(template.component,templateData),{plainText:true});const subject=typeof template.subject==='function'?template.subject(templateData):template.subject;await supabase.from('email_send_log').insert({message_id:messageId,template_name:templateName,recipient_email:to,status:'pending'});const {error}=await supabase.rpc('enqueue_email',{queue_name:'transactional_emails',payload:{message_id:messageId,to,cc,reply_to:replyTo,from:`${SITE_NAME} <noreply@${FROM_DOMAIN}>`,sender_domain:SENDER_DOMAIN,subject,html,text,purpose:'transactional',label:templateName,idempotency_key:idempotencyKey,unsubscribe_token:unsubscribeToken,queued_at:new Date().toISOString()}});if(error)return new Response(JSON.stringify({error:'Failed to enqueue email'}),{status:500,headers:{...corsHeaders,'Content-Type':'application/json'}});return new Response(JSON.stringify({success:true,queued:true}),{status:200,headers:{...corsHeaders,'Content-Type':'application/json'}})})
